version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/notes_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: /home/martin/VisualStudioProjects/notes-app  # Adjust the path to your frontend app
    container_name: notes-frontend
    ports:
      - "3000:3000"  # Assuming your frontend runs on port 3000
    environment:
      - NODE_ENV=development  # Or production, depending on your environment

volumes:
  mysql_data:
