version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-network
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notesdb
      SPRING_DATASOURCE_USERNAME: notes_user
      SPRING_DATASOURCE_PASSWORD: notes_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      - notes-network

volumes:
  mysql-data:

networks:
  notes-network:
    driver: bridge
